---
name: Rule_for_event1
pack: new_proj
description: Sample rule firing on new_proj.event1.
enabled: true
trigger:
    type: new_proj.event1
action:
    ref: new_proj.mcpu
 #executes action new_proj.mcpu
